### PR TITLE
Add API

### PR DESCRIPTION
**Pull request by stvnrlly**
## Tasks
- [x] create API
- [x] POST endpoint for ratings
- [x] GET endpoint for current rating
- [x] GET endpoint for particular date

### CODE REVIEW

**Comment by cmgiven** [comment]
Moved to #7, so I could add a commit that includes nitpicking and the date endpoint.

(By the way, you have push access to this repo. You can create feature branches directly.)

**Comment by cmgiven** [comment]
Deployed.

**Comment by stvnrlly** [comment]
I forgot which permissions I have until I opened the PR 😄 . But on the other hand, you can now add your own commits to forked branches in a PR: https://github.com/blog/2247-improving-collaboration-with-forks.

**Comment by cmgiven** [comment]
Didn't know that. Neat!

**Pull request closed without merging**
